### ISSUE TITLE
install on a MAMP server

### ISSUE THREAD

**Issue by sebababi** [plepe/OpenStreetBrowser#104]
Hello,
Thanks for this great script.

I followed both instructions, 1) INSTALL and  2) more detailed Installation instructions, and none worked on a MacOS Mojave 10.14.3 2,9Ghz intel Core i9 32 Gb RAM

1) For INSTALL I keep on getting: -bash: npm: command not found
I tried many techniques from stackoverflow:
ls ( list command ) shows me that package.json is in the folder openstreetbrowser, so that’s fine.
npm install, npm init, npm run postinstall , npm install package.json ( it seems that the command doesn't work, and can't find the package.json )
full path to npm: /usr/local/bin/npm install
if I check on HD Macintosh/usr/local/bin/ ( there is no file nor folder called npm ), I only have a folder lib and the following files [with an icon EXEC]: NativeNotifier, exiftool, conn_gate, wireshark, edit, twdiff, twfind

When I try the other INSTALLATION option: I get these ERRORs: I read I had to install an older versions: but same thing:

MacBook-Pro:openstreetbrowser sebba$ sudo apt install apache2 libapache2-mod-php git php-cli composer nodejs-legacy npm php-curl
Password:

Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home/bin/apt" (-1)

Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-11.0.3.jdk/Contents/Home/bin/apt" (-1)

Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/apt" (-1)

I reinstalled node.js, and both just installed an alias to npm and an alias to npx (but the source cannot be found), so npm file can’t be found, and the alias is empty, no path.

https://nodejs.org/en/

10.15.3 first.

This package has installed:
    •    Node.js v10.15.3 to /usr/local/bin/node
    •    npm v6.4.1 to /usr/local/bin/npm
Make sure that /usr/local/bin is in your $PATH.

12.2.0 second
This package has installed:
    •    Node.js v12.2.0 to /usr/local/bin/node
    •    npm v6.9.0 to /usr/local/bin/npm
Make sure that /usr/local/bin is in your $PATH.

I tried, again all the previous commands, and at the end when I tried this:

MacBook-Pro:openstreetbrowser sebba$ /usr/local/bin/npm install
-bash: /usr/local/bin/npm: Permission denied

So I tried to give permissions to npm, but it just doesn’t do anything. It doesn’t ask me for password.

MacBook-Pro:openstreetbrowser sebba$ sudo chmod 755 /usr/local/bin/node
Password:
MacBook-Pro:openstreetbrowser sebba$ sudo chmod 755 /usr/local/bin/npm
MacBook-Pro:openstreetbrowser sebba$ sudo chmod 755 /usr/local/bin/npm
MacBook-Pro:openstreetbrowser sebba$ sudo chmod 777 /usr/local/bin/npm
MacBook-Pro:openstreetbrowser sebba$ sudo chmod 777 /usr/local/bin/npm

Also tried:

curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"
-bash: wget: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7039    0  7039    0     0  15105      0 --:--:-- --:--:-- --:--:-- 15072
Password:
installer: Can't load package "/Users/sebba/Downloads/node-latest.pkg": The file “node-latest.pkg” doesn’t exist.

The node-latest.pkg is there. Original size. But when I run the  command, it gets resized to 7kb. And I get the error saying it doesn’t exist. So, makes no sense.

I FINALLY found npm to download.  https://github.com/npm/npm/releases/tag/v6.2.0-next.1
I download it, and is like all the folders and files are not in the correct position, so as it was asking me I was moving the folders to where the: npm install was asking me:

Error: Cannot find module '/usr/local/bin/node_modules/npm/bin/npm-cli.js'

Until I got stocked here:

Error: Cannot find module '../lib/utils/unsupported.js'

https://stackoverflow.com/questions/44363066/error-cannot-find-module-lib-utils-unsupported-js-while-using-ionic

I installed brew from https://brew.sh/

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

sudo rm -rf /usr/local/lib/node_modules/npm
brew reinstall node

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
MacBook-Pro:openstreetbrowser sebba$ upm install
-bash: upm: command not found

But nothing changed

MacBook-Pro:htdocs sebba$ cd openstreetbrowser
MacBook-Pro:openstreetbrowser sebba$ npm install
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /usr/local/bin/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/bin/node_modules/npm/bin/npm-cli.js:148:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
MacBook-Pro:openstreetbrowser sebba$ 

I installed this: https://github.com/nvm-sh/nvm

I installed and reinstalled Brew several times, but Nothing changed

I see the file is there though: ‎/Macintosh HD/usr/local/lib/utils/unsupported.js

Any ideas?

**Comment by dariushazimi** [comment]
did you try `brew install nodejs npm`
